logging:
  level:
    root: INFO
    org:
      springframework:
        web: INFO
    hibernate: 
      SQL: DEBUG
      type: DEBUG

server:
  servlet:
    context-path: /asl-erp/
    session: 
      persistent: true
  port: 8081
  error:
    whitelabel:
      enabled: false
spring:
  profiles: 
    active: dev
  application:
    name: asl-erp
  thymeleaf:
    cache: false
  datasource: 
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://localhost;databaseName=ASLERP
    username: sa
    password: sql@s3rv3r
    tomcat:
      max-wait: 20000
      max-active: 50
      max-idle: 20
      min-idle: 15
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate: 
        dialect: org.hibernate.dialect.SQLServer2012Dialect
        id:
          new_generator_mappings: false
  jackson:
    serialization:
      indent-output: true
  banner:
    location: banner.txt

mybatis: 
#  mapper-locations: classpath*:**/mapper/*.xml
  typeAliasesPackage: com.asl.entity

JNDIName: jdbcTemplate
default: 
  allow-system-admin: N
  site-title: ASL <span class="title-divider">ERP</span>
  logo-name: asl.png
  copyright-text: Powered by <a href="http://www.automationservicesbd.com">ASL</a> &copy; Copyright
  im-ex-path: D:/ASL/importexport
  logging-path: D:/ASL/logs 
  report: 
    template-path: D:/ASL/cr-reports